routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('comment.index'));
});
Route::resource('comment','CommentController');
Route::post('/comment/resstore','CommentController@resstore')->name('comment.resstore');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Illuminate\Support\Facades\Redis;
use App\Entities\Comment;

class CommentController extends Controller
{

    public function index(Request $r)
    {
        $r->validate([
            'channel' => 'max:1024',
        ]);
        if($r->channel == "")return redirect()->route('comment.index',['channel'=>'default']);
        //$comments = Redis::lrange($r->channel,0,29);
        $comments = Comment::get($r->channel);
        $ttl = Comment::getTtl($r->channel);
        //$ranking = Redis::zRevRange('ranking', 0, 29, 'WITHSCORES');
        $ranking = Comment::getRanking($r->channel);
        return view('index')
                ->withChannel($r->channel)
                ->withComments($comments)
                ->withRanking($ranking)
                ->withTtl($ttl)
                ;
    }

    public function show(Request $r)
    {
        $r->validate([
            'channel' => 'max:1024|required',
        ]);
        return $this->list($r->channel);
    }

    private function list($channel)
    {
        $comments = Comment::get($channel);
        $ttl = Comment::getTtl($channel);
        return view('list')
                ->withChannel($channel)
                ->withComments($comments)
                ->withTtl($ttl)
                ;
    }



    public function store(Request $r)
    {
        $r->validate([
            'channel' => 'max:1024',
            'comment' => 'max:4096',
        ]);
        $c = new Comment();
        $c->tc = false;
        $c->body = $r->comment;
        $c->save($r->channel);
        Comment::addRanking($r->channel);
        return redirect()->back();
    }

    public function resstore(Request $r)
    {
        $r->validate([
            'id'         => 'max:1024|required',
            'channel'    => 'max:1024|required',
            'rescomment' => 'max:4096|required',
        ]);
        $newchannel = "res:{$r->channel}:{$r->id}";
        $c = new Comment();
        $c->tc = false;
        $c->body = $r->rescomment;
        $c->save($newchannel);

        $metajson = Redis::get('meta:'.$r->channel);
        $meta = json_decode($metajson,true);
        $res = array_unique(array_merge((array)$meta['res'],[$r->id]));
//元々のメタに自分のレス番に返信あるよ、とマーク。
        Redis::set('meta:'.$r->channel,json_encode([
                            'fchannel' => null,
                            'fid'      => null,
                            'res'      => $res,
                        ]));
//新しい返信ちぇねる用メタ生成
        $exist = Redis::get('meta:'.$newchannel);
        if(empty($exist)){
            Redis::set('meta:'.$newchannel,json_encode([
                                'fchannel' => $r->channel,
                                'fid'      => $r->id,
                                'res'      => [],
                            ]));
        }
        return $this->list($newchannel);
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{{$channel}}} chat</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">


<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
    </head>
    <body style="font-size:medium;background-color:#EEEEFF;">
    <div>
        current channel : {{{$channel}}} (ttl:{{$ttl}}sec)
    </div>
    <hr/>
        <form id ="f1" name="f1" method="post" action="{{route('comment.store')}}">
            comment : <input type="text" id="comment" name="comment"></input>
            <input type="hidden" id="channel" name="channel" value="{{{$channel}}}"></input>
            <input type="hidden" name="_token" value="{{csrf_token()}}">
        </form>
@include('list')
    <hr/>
othoer channels : 
@foreach ($ranking as $cn => $rank)
        <a href="/comment?channel={{{$cn}}}">{{{$cn}}}({{$rank}})</a>
@endforeach
    <hr/>
    <div>
        <form id ="fc" name="fc" method="get" action="{{route('comment.index')}}">
            move channel:<input type="text" id="channel" name="channel"></input>
        </form>
    </div>
    <script type="text/javascript">
    $( '#comment' ).focus();

    function init(pref)
    {
        if(pref == undefined)pref = "";
        pref = pref + " ";
/*
        $(pref + '.resplus' ).click(function(){
            var channel = 'res:'+$(this).data("channel")+":"+$(this).data("comment_id");
            $.ajax({
                        url: '/comment/list',
                        context: this,
                        data: { channel: channel},
                        success: function(data){
                                    $(this).hide();
                                    $($(this).data("id")).html(data);
                                    init($(this).data("id"));
                                }
            });
        });
*/
        $(pref + '.resplus' ).each(function(){
            var channel = 'res:'+$(this).data("channel")+":"+$(this).data("comment_id");
            $.ajax({
                        url: '/comment/list',
                        context: this,
                        data: { channel: channel},
                        success: function(data){
                                    $(this).hide();
                                    $($(this).data("id")).html(data);
                                    init($(this).data("id"));
                                }
            });
        });

        $(pref+ '.res' ).click(function(){
            var formid = $(this).data('form');
            $(formid).show();
            $(this).hide();
        });


        $(pref+'.resinput').keypress(function (e) {
            if (e.keyCode == 13){
                var formid = $(this).data('form');
                $.ajax({
                   type: 'POST',
                   url: '/comment/resstore',
                   context: this,
                   data: $(formid).serialize(),
                   success: function(data){
                                $(this).hide();
                                $($(this).data("id")).html(data);
                                init($(this).data("id"));
                           }
                });
                var formid = $(this).data('form');
                $(formid).hide();
            }
        });


    }
    init();
    </script>
    </body>
</html>

resources/views/list.blade.php
@foreach ($comments as $comment)
    <div style="font-size:medium;margin:10px;width:400px;border-left: solid 1px #C0C0F0;">
        {{{$comment->body}}}
            @php
            $viewid = md5(rand(1,1000000));
            $formid = md5(rand(1,1000000));
            $formdivid = md5(rand(1,1000000));
            @endphp
            <span class="res" data-id="{{$comment->id}}" data-form="#{{$formdivid}}" data-channel="{{$channel}}" style="cursor:pointer;text-decoration: underline;color:#0000FF;font-size:small">[res]</span>
            <div id="{{$formdivid}}" style="display:none;">
                <form id ="{{$formid}}" name="res" method="post" action="{{route('comment.resstore')}}">
                    res : <input type="text" class="resinput" id="rescomment" name="rescomment" data-id="#{{$viewid}}" data-form="#{{$formid}}"></input>
                    <input type="text" name="dummy"  style="display:none;"></input>
                    <input type="hidden" id="channel" name="channel" value="{{{$channel}}}"></input>
                    <input type="hidden" id="id" name="id" value="{{{$comment->id}}}"></input>
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                </form>
            </div>
            <div id="{{$viewid}}">
                @if ($comment->tc)
                    <span class="resplus" data-id="#{{$viewid}}" data-comment_id="{{$comment->id}}" data-channel="{{$channel}}" style="cursor:pointer;text-decoration: underline;color:#0000FF;font-size:small">[+]</span>
                @endif
            </div>
    </div>
@endforeach